actions:
  pre:
    install-omz: git clone --depth 1 https://github.com/ohmyzsh/ohmyzsh.git ~/.oh-my-zsh;
      git clone https://github.com/zsh-users/zsh-autosuggestions ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions;
      git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
    install-spacevim: git clone --depth 1 https://github.com/SpaceVim/SpaceVim.git
      ~/.SpaceVim; ln -s ~/.SpaceVim ~/.config/nvim
config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
dotfiles:
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
    actions:
    - install-omz
  d_alacritty:
    src: config/alacritty
    dst: ~/.config/alacritty
  d_conky:
    src: config/conky
    dst: ~/.config/conky
  d_feh:
    src: config/feh
    dst: ~/.config/feh
  d_fontconfig:
    src: config/fontconfig
    dst: ~/.config/fontconfig
  d_i3:
    src: config/i3
    dst: ~/.config/i3
  d_mpv:
    src: config/mpv
    dst: ~/.config/mpv
    upignore:
    - _cache
    cmpignore:
    - _cache
  d_picom:
    src: config/picom
    dst: ~/.config/picom
  d_pip:
    src: config/pip
    dst: ~/.config/pip
  d_polybar:
    src: config/polybar
    dst: ~/.config/polybar
  d_wallpaper:
    src: wallpaper
    dst: ~/.wallpaper
    upignore:
    - '!67501250_p0.jpg'
    - '[a-zA-Z0-9]*'
    cmpignore:
    - '*'
  f_xresources:
    src: Xresources
    dst: ~/.Xresources
  d_networkmanager-dmenu:
    src: config/networkmanager-dmenu
    dst: ~/.config/networkmanager-dmenu
  f_npmrc:
    src: npmrc
    dst: ~/.npmrc
    chmod: '600'
  d_spacevim.d:
    src: SpaceVim.d
    dst: ~/.SpaceVim.d
    actions:
    - install-spacevim
profiles:
  arch:
    dotfiles:
    - f_zshrc
    - d_alacritty
    - d_conky
    - d_feh
    - d_fontconfig
    - d_i3
    - d_mpv
    - d_picom
    - d_pip
    - d_polybar
    - d_wallpaper
    - f_xresources
    - d_networkmanager-dmenu
    - f_npmrc
    - d_spacevim.d
