#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2022 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "material"
    colorscheme_bg = "dark"
    guifont = "FiraCode Nerd Font:h11"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "slant"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false

    default_indent = 4
    vim_help_language = "cn"
    enable_vimfiler_welcome = false
    bootstrap_before = "myspacevim#before"
    #bootstrap_after  = "myspacevim#after"

# Enable autocomplete layer
[[layers]]
    name = 'autocomplete'
    auto_completion_return_key_behavior = "complete"
    auto_completion_tab_key_behavior = "smart"

[[layers]]
    name = 'shell'
    default_position = 'top'
    default_height = 30

[[layers]]
    name = "chinese"

[[layers]]
    name = "colorscheme"

[[layers]]
    name = "fzf"

[[layers]]
    name = "git"

[[layers]]
    name = "incsearch"

[[layers]]
    name = "sudo"

[[layers]]
    name = "tools"

[[layers]]
    name = "VersionControl"

[[layers]]
    name = "lsp"
    enabled_clients = ["pyright"]

[[layers]]
    name = "lang#python"
    enable_typeinfo = true
    format_on_save = true
    python_linters = ["python"]
    python_file_head = [
        "#!/usr/bin/env python"
        ""
        ""
    ]

[[layers]]
    name = "lang#sh"

[[layers]]
    name = "lang#toml"
